#!/usr/bin/env python3
"""Emit LaTeX macros (paper_numbers.tex) for every corpus-derived number the
paper quotes, so the manuscript never hand-transcribes a stale count again.

Single source of truth: the same derived artifacts the fail-closed table
generator reads (derived/*.json, derived/admission_sensitivity.csv,
dataset.meta.json). Re-run after `make derived` whenever the corpus advances;
main.tex \\input{paper_numbers.tex} and uses the macros.

Output target is the Overleaf project dir so the paper picks it up on its next
compile (the path is configurable via --out).
"""
from __future__ import annotations

import argparse
import collections
import csv
import glob
import json
import pathlib

import yaml

REPO = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "6a1d66df502cdc827ad0999d" / "paper_numbers.tex"

# LaTeX control sequences must be letters only — map layer ids to letter names.
LAYER_CS = {
    "l0_network": "Lzero",
    "l1_consensus": "Lone",
    "l3_rpc": "Lthree",
    "l4_frontend": "Lfour",
    "asset_onchain": "Asset",
    "offramp_cex": "Offramp",
}
ARCH_CS = {
    "cex_only": "Cex",
    "null_event": "Null",
    "frontend_only": "Frontend",
    "multi_layer": "Multi",
    "asset_only": "Asset",
    "other_single_layer": "Other",
}


def _load_json(rel: str):
    return json.loads((REPO / rel).read_text())


def _pct(num: int, den: int) -> str:
    return f"{100.0 * num / den:.1f}" if den else "0.0"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    meta = _load_json("dataset.meta.json")
    snap = _load_json("derived/coverage_matrix.json")["meta"]["dataset_snapshot"]
    layers = _load_json("derived/layer_observability.json")
    archs = _load_json("derived/event_archetypes.json")

    status = snap["counts_by_status"]
    n_admit = status["admitted"]
    lines = [
        "% AUTO-GENERATED by scripts/build_paper_macros.py — DO NOT EDIT BY HAND.",
        "% Regenerate with `make paper-macros` or the full `make regenerate` gate.",
        f"% snapshot {meta['dataset_version']} · commit {meta['source_commit']} "
        f"· cutoff {meta['cutoff_date']} · generated {meta['generated_at']}",
        "",
        "% --- corpus ---",
        f"\\newcommand{{\\corpusN}}{{{n_admit}}}",
        f"\\newcommand{{\\corpusTotal}}{{{meta['event_count']}}}",
        f"\\newcommand{{\\corpusDraft}}{{{status['draft']}}}",
        f"\\newcommand{{\\corpusReject}}{{{status['rejected']}}}",
        "",
        "% --- layer observability (changed / measured+partial) ---",
    ]
    for row in layers:
        cs = LAYER_CS.get(row["layer"])
        if not cs:
            continue
        meas = row["measured_count"]
        part = row["partially_measured_count"]
        gap = row["not_measured_count"]
        den = meas + part
        num = row["changed_under_measured_or_partial_count"]
        lines += [
            f"\\newcommand{{\\{cs}Meas}}{{{meas}}}",
            f"\\newcommand{{\\{cs}Part}}{{{part}}}",
            f"\\newcommand{{\\{cs}Gap}}{{{gap}}}",
            f"\\newcommand{{\\{cs}Den}}{{{den}}}",
            f"\\newcommand{{\\{cs}Num}}{{{num}}}",
            f"\\newcommand{{\\{cs}Rate}}{{{num}/{den}}}",
            f"\\newcommand{{\\{cs}Pct}}{{{_pct(num, den)}}}",
        ]
    lines.append("")
    lines.append("% --- archetypes (share of admitted corpus) ---")
    counts: dict[str, int] = {}
    for e in archs:
        counts[e["derived_archetype"]] = counts.get(e["derived_archetype"], 0) + 1
    for arch, cs in ARCH_CS.items():
        c = counts.get(arch, 0)
        lines += [
            f"\\newcommand{{\\arch{cs}}}{{{c}}}",
            f"\\newcommand{{\\arch{cs}Pct}}{{{_pct(c, n_admit)}}}",
        ]
    lines.append("")
    lines.append("% --- strata / case-roles / temporal tiers / jurisdiction (admitted) ---")
    adm = []
    for f in sorted(glob.glob(str(REPO / "events" / "*.yaml"))):
        d = yaml.safe_load(open(f))
        if isinstance(d, dict) and d.get("status") == "admitted":
            adm.append(d)
    strat = collections.Counter(d.get("research_stratum") for d in adm)
    role = collections.Counter(d.get("admission_tier") for d in adm)
    ttier = collections.Counter(d.get("temporal_tier") for d in adm)
    jur_us = sum(1 for d in adm if "US" in (
        [d.get("jurisdiction")] if isinstance(d.get("jurisdiction"), str)
        else (d.get("jurisdiction") or [])))
    STRAT_CS = {"S1_ofac_sdn": "StratOfac", "S2_ofac_removal": "StratOfacRem",
                "S3_doj_sec_cftc_fiod": "StratDoj", "S4_nation_state": "StratNation",
                "S5_corporate": "StratCorp", "S6_supranational": "StratSupra"}
    ROLE_CS = {"anchor_case": "RoleAnchor", "empirical_case": "RoleEmpirical",
               "null_case": "RoleNull"}
    TTIER_CS = {"discovery_only_2007_2012": "TierDiscovery",
                "historical_baseline_2013_2016": "TierHistorical",
                "comparable_main_2017_present": "TierComparable"}
    for k, cs in STRAT_CS.items():
        lines.append(f"\\newcommand{{\\{cs}}}{{{strat.get(k, 0)}}}")
    for k, cs in ROLE_CS.items():
        lines.append(f"\\newcommand{{\\{cs}}}{{{role.get(k, 0)}}}")
    for k, cs in TTIER_CS.items():
        lines.append(f"\\newcommand{{\\{cs}}}{{{ttier.get(k, 0)}}}")
    lines.append(f"\\newcommand{{\\JurUS}}{{{jur_us}}}")
    lines.append(f"\\newcommand{{\\JurUSPct}}{{{_pct(jur_us, n_admit)}}}")
    jur = collections.Counter()
    for d in adm:
        j = d.get("jurisdiction")
        j = [j] if isinstance(j, str) else (j or [])
        for x in j:
            jur[x] += 1
    JUR_CS = {"corporate_global": "JurCorpGlobal", "EU": "JurEU", "RU": "JurRU",
              "UK": "JurUK", "CN": "JurCN", "JP": "JurJP"}
    for k, cs in JUR_CS.items():
        lines.append(f"\\newcommand{{\\{cs}}}{{{jur.get(k, 0)}}}")
    prec = collections.Counter((d.get("trigger") or {}).get("timestamp_precision") for d in adm)
    hourbetter = ("second", "minute", "hour", "hour_range")
    lines.append(f"\\newcommand{{\\PrecHourBetter}}{{{sum(prec[p] for p in hourbetter)}}}")
    lines.append(f"\\newcommand{{\\PrecDayCoarser}}{{{prec['day'] + prec['week']}}}")
    lines.append(f"\\newcommand{{\\PrecDay}}{{{prec['day']}}}")
    lines.append(f"\\newcommand{{\\PrecWeek}}{{{prec['week']}}}")
    # latency-precision accounting: event_metrics carries trigger_is_action
    # (t=0 record-level identity rows, excluded from reaction-latency).
    metrics = _load_json("derived/event_metrics.json")
    tia = {r["event_id"]: r.get("trigger_is_action") for r in metrics}
    n_action = sum(1 for d in adm if tia.get(d.get("id")))
    n_hour_nonaction = sum(
        1 for d in adm
        if (d.get("trigger") or {}).get("timestamp_precision") in hourbetter
        and not tia.get(d.get("id")))
    lines.append(f"\\newcommand{{\\TriggerIsAction}}{{{n_action}}}")
    lines.append(f"\\newcommand{{\\PrecHourNonAction}}{{{n_hour_nonaction}}}")
    n_privtool = sum(1 for r in metrics if r.get("target_is_privacy_tool"))
    lines.append(f"\\newcommand{{\\PrivacyToolTargets}}{{{n_privtool}}}")

    lines.append("")
    lines.append("% --- admission-sensitivity ablation (strict/current/permissive) ---")
    with (REPO / "derived" / "admission_sensitivity.csv").open() as f:
        for r in csv.DictReader(f):
            cs = LAYER_CS.get(r["layer"])
            if not cs:
                continue
            for rubric, col in (("Strict", "strict_rate"),
                                ("Current", "current_rate"),
                                ("Perm", "permissive_rate")):
                val = r[col].strip()
                if val:
                    lines.append(
                        f"\\newcommand{{\\{cs}{rubric}}}{{{float(val):.2f}}}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines).rstrip() + "\n")
    print(f"[macros] wrote {args.out} ({sum(1 for l in lines if l.startswith(chr(92)+'newcommand'))} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
