#!/usr/bin/env python3
"""Emit LaTeX macros (paper_numbers.tex) for every corpus-derived number the
paper quotes, so the manuscript never hand-transcribes a stale count again.

Single source of truth: the same derived artifacts the fail-closed table
generator reads (derived/*.json, derived/admission_sensitivity.csv,
dataset.meta.json). Re-run after `make derived` whenever the corpus advances;
main.tex \\input{paper_numbers.tex} and uses the macros.

Output target is the Overleaf project dir so the paper picks it up on its next
compile (the path is configurable via --out).
"""
from __future__ import annotations

import argparse
import csv
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "6a1d66df502cdc827ad0999d" / "paper_numbers.tex"

# LaTeX control sequences must be letters only — map layer ids to letter names.
LAYER_CS = {
    "l0_network": "Lzero",
    "l1_consensus": "Lone",
    "l3_rpc": "Lthree",
    "l4_frontend": "Lfour",
    "asset_onchain": "Asset",
    "offramp_cex": "Offramp",
}
ARCH_CS = {
    "cex_only": "Cex",
    "null_event": "Null",
    "frontend_only": "Frontend",
    "multi_layer": "Multi",
    "asset_only": "Asset",
    "other_single_layer": "Other",
}


def _load_json(rel: str):
    return json.loads((REPO / rel).read_text())


def _pct(num: int, den: int) -> str:
    return f"{100.0 * num / den:.1f}" if den else "0.0"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    meta = _load_json("dataset.meta.json")
    snap = _load_json("derived/coverage_matrix.json")["meta"]["dataset_snapshot"]
    layers = _load_json("derived/layer_observability.json")
    archs = _load_json("derived/event_archetypes.json")

    status = snap["counts_by_status"]
    n_admit = status["admitted"]
    lines = [
        "% AUTO-GENERATED by scripts/build_paper_macros.py — DO NOT EDIT BY HAND.",
        "% Regenerate with `make paper-macros` or the full `make regenerate` gate.",
        f"% snapshot {meta['dataset_version']} · commit {meta['source_commit']} "
        f"· cutoff {meta['cutoff_date']} · generated {meta['generated_at']}",
        "",
        "% --- corpus ---",
        f"\\newcommand{{\\corpusN}}{{{n_admit}}}",
        f"\\newcommand{{\\corpusTotal}}{{{meta['event_count']}}}",
        f"\\newcommand{{\\corpusDraft}}{{{status['draft']}}}",
        f"\\newcommand{{\\corpusReject}}{{{status['rejected']}}}",
        "",
        "% --- layer observability (changed / measured+partial) ---",
    ]
    for row in layers:
        cs = LAYER_CS.get(row["layer"])
        if not cs:
            continue
        meas = row["measured_count"]
        part = row["partially_measured_count"]
        gap = row["not_measured_count"]
        den = meas + part
        num = row["changed_under_measured_or_partial_count"]
        lines += [
            f"\\newcommand{{\\{cs}Meas}}{{{meas}}}",
            f"\\newcommand{{\\{cs}Part}}{{{part}}}",
            f"\\newcommand{{\\{cs}Gap}}{{{gap}}}",
            f"\\newcommand{{\\{cs}Den}}{{{den}}}",
            f"\\newcommand{{\\{cs}Num}}{{{num}}}",
            f"\\newcommand{{\\{cs}Rate}}{{{num}/{den}}}",
            f"\\newcommand{{\\{cs}Pct}}{{{_pct(num, den)}}}",
        ]
    lines.append("")
    lines.append("% --- archetypes (share of admitted corpus) ---")
    counts: dict[str, int] = {}
    for e in archs:
        counts[e["derived_archetype"]] = counts.get(e["derived_archetype"], 0) + 1
    for arch, cs in ARCH_CS.items():
        c = counts.get(arch, 0)
        lines += [
            f"\\newcommand{{\\arch{cs}}}{{{c}}}",
            f"\\newcommand{{\\arch{cs}Pct}}{{{_pct(c, n_admit)}}}",
        ]
    lines.append("")
    lines.append("% --- admission-sensitivity ablation (strict/current/permissive) ---")
    with (REPO / "derived" / "admission_sensitivity.csv").open() as f:
        for r in csv.DictReader(f):
            cs = LAYER_CS.get(r["layer"])
            if not cs:
                continue
            for rubric, col in (("Strict", "strict_rate"),
                                ("Current", "current_rate"),
                                ("Perm", "permissive_rate")):
                val = r[col].strip()
                if val:
                    lines.append(
                        f"\\newcommand{{\\{cs}{rubric}}}{{{float(val):.2f}}}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines).rstrip() + "\n")
    print(f"[macros] wrote {args.out} ({sum(1 for l in lines if l.startswith(chr(92)+'newcommand'))} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
